(define (make-account balance secret_passwd)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input_passwd m)
    (if (not (eq? secret_passwd input_passwd)) 
     (error "Incorrect password" input_passwd)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m)))))
  dispatch)
(define (make-joint account account-password new-password)
  (define (dispatch password m)
    (if (eq? password new-password)
      (account account-password m)
      (error "Incorrect password")))
  dispatch)

