(define (make-account balance secret_passwd);;(1)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input_passwd m);;(2)
   (if (not (eq? secret_passwd input_passwd)) (error "Incorrect password" input_passwd);;(3)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m)))))
  dispatch)
